#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) struct MenuItem {
    pub(crate) label: &'static str,
    pub(crate) shortcut: Option<&'static str>,
    pub(crate) command: MenuCommand,
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub(crate) enum MenuCommand {
    NewFile,
    Save,
    Quit,
    ToggleSidebar,
    Find,
    ToggleSearchCase,
    Undo,
    Redo,
    DeletePreviousWord,
    DeleteNextWord,
    DeleteToLineEnd,
    FindNext,
    FindPrevious,
    GoToLine,
    ToggleLineNumbers,
    CycleTheme,
    CycleSyntaxTheme,
    ToggleReaderMode,
    DecreaseReaderSpeed,
    IncreaseReaderSpeed,
    ToggleWrap,
    PageUp,
    PageDown,
    DocumentStart,
    DocumentEnd,
    PreviousWord,
    NextWord,
    PreviousTab,
    NextTab,
    CloseTab,
    SaveCurrentWorkspace,
    SaveNamedWorkspace,
    ListWorkspaces,
    OpenWorkspace,
    DeleteWorkspace,
    OpenCurrentWorkspace,
    ToggleRestoreLastWorkspace,
    OpenHelp,
    OpenCommandPalette,
    HelpOnly,
}
